# Use official Node image
FROM node:20-alpine

# Update system packages to patch vulnerabilities
RUN apk update && apk upgrade && \
    rm -rf /var/cache/apk/*

    
# Create app directory inside container
WORKDIR /app

# Copy package files first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy remaining project files
COPY . .

# Expose backend port
EXPOSE 5000

# Start application
CMD ["npm", "start"]





